def provide_feedback(user_output, expected_output):
    """
    Provides basic feedback when the user's output is incorrect.

    Args:
        user_output (str): The output generated by user code.
        expected_output (str): The correct expected output.

    Returns:
        str: Feedback message.
    """
    if user_output == expected_output:
        return "Great job! Your solution is correct. ✅"

    if user_output.isnumeric() and expected_output.isnumeric():
        return "Check your arithmetic calculations. Maybe a small mistake? 🧐"

    return "Your answer is incorrect. Try revisiting the logic and debugging your code. 🔎"
